version: "3"
services:
  mysql:
    image: "mysql:latest"
    restart: always
    volumes:
      - /home/ubuntu/mysql_vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - net
  redis:
    image: "redis:latest"
    networks:
      - net
  elasticsearch:
    image: "elasticsearch:7.10.1"
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - net
  nginx:
    depends_on:
      - server
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - net
  server:
    depends_on:
      - mysql
      - redis
      - elasticsearch
    build:
      context: .
    networks:
      - net
    environment:
      - REDIS_URL=redis
      - ELASTICSEARCH_URL=elasticsearch
      - DATABASE_URL=mysql
      - MYSQL_ROOT_PASSWORD
      - MAIL_SERVER
      - MAIL_USERNAME
      - MAIL_PASSWORD
volumes:
  elasticsearch_data:
    driver: local
networks:
  net:
