version: "3"
services:
  mysql:
    image: mariadb:latest
    restart: always
    volumes:
      - /home/marco/data/mysql_vol:/var/lib/postgresql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=microblog
    networks:
      - net
  redis:
    image: "redis:latest"
    command: '--requirepass password'
    networks:
      - net
  elasticsearch:
    image: "elasticsearch:7.10.1"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - net
  nginx:
    depends_on:
      - server
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - net
  server:
    depends_on:
      - mysql
      - redis
      - elasticsearch
    build:
      context: .
    networks:
      - net
    environment:
      - REDIS_URL=redis
      - REDIS_PASSWORD=password
      - ELASTICSEARCH_URL=elasticsearch
      - DATABASE_URL=mysql
      - DATABASE_NAME=microblog
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
      - MAIL_SERVER=smtp.qq.com
      - MAIL_USERNAME=adiachan@foxmail.com
      - MAIL_PASSWORD=undffmpamglhbhdd
volumes:
  elasticsearch_data:
    driver: local
networks:
  net:
