"""new fields in user model

Revision ID: 25635c945af9
Revises: 42301c1dc4a8
Create Date: 2019-07-06 19:44:32.258196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25635c945af9'
down_revision = '42301c1dc4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
